name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Pull latest code
        run: |
          cd /home/khanh/syb2013_test  # Thay đổi đường dẫn đến thư mục ứng dụng
          git pull origin main
      - name: Install dependencies
        run: |
          cd /home/khanh/syb2013_test
          npm ci
      - name: Restart PM2
        run: pm2 restart 3
